model:
  img_size: 128
  patch_size: 4
  in_chans: 48
  embed_dim: 240
  depths: [2, 2, 6, 2]
  num_heads: [4, 4, 8, 16]
  window_size: 8
  mlp_ratio: 4.0
  out_channels: 3
dataset:
  train_data_path: /path/to/the/training_set
  val_data_path: /path/to/the/validation_set
#
batch_size: 48
epochs: 1000
num_workers: 8
use_pretrained: False
checkpoint_dir: ..\checkpoints
checkpoint_id: mg2l_epoch1000
#
lr: 1e-4
decay_epochs: 50
decay_rate: 0.999
# for prediction
predict_input: ..\examples\input_data.h5
